name: OWASP ZAP Scan

on:
  pull_request:
    branches:
      - main  # Trigger ZAP scan on PRs targeting the `main` branch
  push:
    branches:
      - main  # Or trigger on push to the `main` branch

permissions:
  contents: read  # Adjust permissions as needed

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python (optional, if your application is Python-based)
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: 'https://www.medium.com/'
          token: ${{ secrets.GITHUB_TOKEN }}
          debug: true  # Enable debug mode for detailed logs
